# Generated by Django 3.2.6 on 2021-09-06 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Категория')),
            ],
        ),
        migrations.CreateModel(
            name='Number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Идентификатор')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('Matrix', 'Матрикс'), ('Estel', 'Эстель')], default='Matrix', max_length=32, verbose_name='Бренд')),
                ('volume', models.PositiveSmallIntegerField(default=0, verbose_name='Объем')),
                ('quantity', models.PositiveSmallIntegerField(default=0, verbose_name='Количество')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WareHouse.category')),
                ('number', models.ForeignKey(max_length=256, on_delete=django.db.models.deletion.CASCADE, to='WareHouse.number')),
            ],
        ),
    ]
