# Generated by Django 3.2.6 on 2021-09-08 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WareHouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='tracked',
            field=models.BooleanField(default=False, verbose_name='Отслеживаемость'),
        ),
    ]
