# Generated by Django 3.2.6 on 2021-09-09 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WareHouse', '0003_alter_material_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='number',
            field=models.ForeignKey(max_length=256, on_delete=django.db.models.deletion.CASCADE, to='WareHouse.number', verbose_name='Номер'),
        ),
    ]
