# Generated by Django 3.2.6 on 2021-08-11 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=15, verbose_name='Имя')),
                ('datetime', models.TimeField(auto_now_add=True, verbose_name='Дата посещения')),
                ('t_number', models.SmallIntegerField(unique=True, verbose_name='Номер телефона')),
            ],
        ),
        migrations.CreateModel(
            name='MaleHaircut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveSmallIntegerField(choices=[(600, 'Модельная'), (250, 'Наголо'), (350, 'Одна насадка'), (400, 'Две насадки'), (500, 'Коррекция'), (700, 'Модельная удлиненная'), (250, 'Борода под насадку'), (400, 'Оформление бороды'), (150, 'Окантовка'), (500, 'Детям до 6 лет'), (550, 'Детям до 6 лет удлиненная'), (50, 'Полоски'), (400, 'Рисунок на голове')], verbose_name='Тип')),
            ],
        ),
        migrations.CreateModel(
            name='MaleClient',
            fields=[
                ('client_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='CashBox.client')),
            ],
            bases=('CashBox.client',),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('haircut', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='CashBox.malehaircut')),
            ],
        ),
        migrations.CreateModel(
            name='MaleCLientService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('male_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CashBox.service')),
                ('male_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CashBox.maleclient')),
            ],
        ),
        migrations.AddField(
            model_name='maleclient',
            name='service',
            field=models.ManyToManyField(through='CashBox.MaleCLientService', to='CashBox.Service'),
        ),
    ]
