# Generated by Django 3.2.6 on 2021-08-14 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CashBox', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maleclient',
            name='service',
            field=models.ManyToManyField(through='CashBox.MaleClientService', to='CashBox.Service'),
        ),
    ]
