# Generated by Django 3.2.6 on 2021-09-14 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CashBox', '0002_alter_maleclient_service'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='MaleClient',
        ),
        migrations.DeleteModel(
            name='MaleCLientService',
        ),
        migrations.DeleteModel(
            name='MaleHaircut',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
